### PR TITLE
Fixed final animation error

### PR DESCRIPTION
**Pull request by Abg4real**
Hi Kanishk Bhaiyya!
Sorry I took a long time. Actually I had solved it but had forgotten to create a pull request.
Before:
96358931-388d1200-112a-11eb-9642-6b0b2c6584c8
After:
image
Please check to see if it is working.
Abhishek.

### CODE REVIEW

**Comment by gkanishk** [comment]
Thanks for the PR I will check 😊

**Comment by Abg4real** [comment]
Thanks for merging. 
Sorry to message you here but I don't have your any other mode of contact. I checked your projects from Tanay Pratap's job challenge web site and the projects are really awesome. 
I know good amount of react and javascript both but I am not really confident about it. So I wish to improve. 
Can you suggest any good resources and/or roadmap to learn javascript and react?

**Comment by gkanishk** [comment]
@Abg4real have you taken part in neoGcamp?
So if you're good in React just keep building good projects only then you'll gain confidence share with community and gain feedbacks you can join TeamTanay discord server everyone helps each other there so that will be good place to hang out. And you can contact be there too😊

**Comment by Abg4real** [comment]
@gkanishk Yes I have and I am doing the projects. I hope to achieve some confidence via that. Thanks a lot!😄

**Pull request merged**
